# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.ssh.forward_agent = true
  config.vm.synced_folder "../", "/dotfiles"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

  config.vm.provision "shell", path: "provision.sh", env: {"USER" => "vagrant"}
end
