tap "borgbackup/tap"
tap "buo/cask-upgrade"
tap "d12frosted/emacs-plus"
tap "golangci/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "timescale/tap"
brew "apr-util"
brew "readline"
brew "xz"
brew "python@3.9"
brew "aspell"
brew "gettext"
brew "libffi"
brew "glib"
brew "m4"
brew "autoconf"
brew "automake"
brew "awscli"
brew "azure-cli"
brew "bash"
brew "bazel"
brew "bazelisk", link: false
brew "berkeley-db@4"
brew "binutils"
brew "bison"
brew "boost"
brew "pkg-config"
brew "cairo"
brew "ccls"
brew "cmake"
brew "coreutils"
brew "curl"
brew "cyrus-sasl"
brew "diffutils"
brew "dockutil"
brew "expat"
brew "libtool"
brew "gnutls"
brew "gobject-introspection"
brew "harfbuzz"
brew "libass"
brew "libsodium"
brew "zeromq"
brew "ffmpeg"
brew "gcc"
brew "file-formula"
brew "flex"
brew "gawk"
brew "gifsicle"
brew "git"
brew "libgpg-error"
brew "libgcrypt"
brew "gmime"
brew "go"
brew "go-bindata"
brew "go-md2man"
brew "gopls"
brew "gpatch"
brew "pango"
brew "librsvg"
brew "graphviz"
brew "gzip"
brew "hidapi"
brew "htop"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "inlets"
brew "intltool"
brew "ispell"
brew "istioctl"
brew "isync", restart_service: true, link: false
brew "jq"
brew "kubernetes-cli"
brew "ldns"
brew "less"
brew "libhandy"
brew "libpgm"
brew "libunwind-headers"
brew "libvterm"
brew "links"
brew "mailutils"
brew "make"
brew "mas"
brew "minikube"
brew "miniupnpc"
brew "mp3info"
brew "msmtp"
brew "xapian"
brew "mu"
brew "multimarkdown"
brew "mysql-client"
brew "ninja"
brew "nmap"
brew "node"
brew "nss"
brew "oauth2l"
brew "openapi-generator"
brew "p7zip"
brew "plantuml"
brew "qt"
brew "poppler"
brew "postgresql"
brew "protobuf"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pyenv-virtualenvwrapper"
brew "python@3.8"
brew "qemu"
brew "qt@5"
brew "r"
brew "ruby-build"
brew "rbenv"
brew "rename"
brew "ripgrep"
brew "rsync"
brew "ruby"
brew "s3cmd"
brew "scc"
brew "screen"
brew "shfmt"
brew "simple-scan"
brew "sloccount"
brew "subversion"
brew "syncthing", restart_service: true
brew "topgrade"
brew "tree"
brew "unzip"
brew "vegeta"
brew "vim"
brew "vips"
brew "watch"
brew "watchexec"
brew "watchman"
brew "websocat"
brew "wget"
brew "yq"
brew "borgbackup/tap/borgbackup-fuse"
brew "d12frosted/emacs-plus/emacs-plus@27", args: ["with-mailutils", "with-nobu417-big-sur-icon"]
brew "golangci/tap/golangci-lint"
cask "aldente"
cask "alfred3"
cask "android-file-transfer"
cask "android-platform-tools"
cask "anki"
cask "docker"
cask "font-source-code-pro"
cask "gimp"
cask "google-chrome-beta"
cask "google-cloud-sdk"
cask "google-earth-pro"
cask "googleappengine"
cask "gutenprint"
cask "handbrake"
cask "iterm2"
cask "karabiner-elements"
cask "macfuse"
cask "mactex"
cask "mono-mdk"
cask "ngrok"
cask "plex"
cask "rar"
cask "signal"
cask "spotify"
cask "tor-browser"
cask "transmission"
cask "visual-studio-code-insiders"
cask "vlc"
cask "vorta"
cask "whatsapp"
cask "wireshark"
cask "xquartz"
cask "zoom"
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Developer", id: 640199958
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tailscale", id: 1475387142
mas "Userscripts", id: 1463298887
mas "Vimari", id: 1480933944
mas "Wayback Machine", id: 1472432422
mas "WireGuard", id: 1451685025
